export const STOREPRODUCTS = "STOREPRODUCTS";

export const ISLOADING = "ISLOADING";
export const STOREDATA = "STOREDATA";
export const STOREPRODUCT = "STOREPRODUCT";
export const STORETABLEDATA = "STORETABLEDATA";
export const STOREPRODUCTSMAXSUMTOTAL = "STOREPRODUCTSMAXSUMTOTAL";
export const STOREPRODUCTSMINSUMTOTAL = "STOREPRODUCTSMINSUMTOTAL";
export const STOREPRODUCTSAVERAGETOTAL = "STOREPRODUCTSAVERAGETOTAL";
export const STOREPRODUCTPRICEWEEK = "STOREPRODUCTPRICEWEEK";
export const STORECURRPRODUCTPRICEWEEK = "STORECURRPRODUCTPRICEWEEK";

export const ONSEARCHCHANGE = "ONSEARCHCHANGE";
export const CREATEREPORT = "CREATEREPORT";

export const VALUEFROM = "VALUEFROM";
export const VALUETO = "VALUETO";
export const SETVALUEPICKER = "SETVALUEPICKER";
export const HANDLECHANGE = "HANDLECHANGE";

export const SETDIRECTIONSORT = "SETDIRECTIONSORT";

export const INPUT = "INPUT";
export const EMAILINPUT = "EMAILINPUT";
export const STATEINPUT = "STATEINPUT";

export const ADDITEM = "ADDITEM";
export const CLEARITEM = "CLEARITEM";
export const ADDINPUT = "ADDINPUT";
export const ADDEMAILINPUT = "ADDEMAILINPUT";
export const ADDSTATEINPUT = "ADDSTATEINPUT";

export const CLEARINPUT = "CLEARINPUT";
export const CLEAREMAILINPUT = "CLEAREMAILINPUT";
export const CLEARSTATEINPUT = "CLEARSTATEINPUT";

export const REMOVEINPUTITEM = "REMOVEINPUTITEM";
export const REMOVEEMAILITEM = "REMOVEEMAILITEM";
export const REMOVEITEMSTATEITEM = "REMOVEITEMSTATEITEM";

export const REMOVEITEMS = "REMOVEITEMS";
export const REMOVESTATEITEM = "REMOVESTATEITEM";

export const BACKSPACEINPUT = "BACKSPACEINPUT";
export const BACKSPACEEMAIL = "BACKSPACEEMAIL";
export const BACKSPACESTATE = "BACKSPACESTATE";

export const ISBUTTONACTIVE = "ISBUTTONACTIVE";

export const EMAILINPUTSTATUSBTN = "EMAILINPUTSTATUSBTN";
